"""
Django settings for evento_qr project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!!cc&lrmf-k)4$)#+7k(00osv62%(($$77wsr5@_vd(lf&)z7='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1', 
    'localhost',
    '*',  # ← Agregar tu dominio ngrok
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'channels', 
     'corsheaders', 
    'invitados',  # ← Añadir esta línea
]


# Configuración de Django Channels



MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Configuración CORS para desarrollo
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'evento_qr.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'evento_qr.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {  # ✅ Clave 'default' requerida
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'evento_qr_db',
        'USER': 'postgres',
        'PASSWORD': 'Saladin0',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/



USE_TZ = True  # ✅ Mantener activado
USE_I18N = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configurar archivos estáticos y media
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Configurar idioma
LANGUAGE_CODE = 'es-mx'
TIME_ZONE = 'America/Mexico_City'

# URLs de autenticación
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'


# Configuración CSRF para ngrok
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'https://*.ngrok-free.app',  # Permite cualquier dominio ngrok con HTTPS
    'https://*.ngrok.io',
    'https://*.ngrok.app',
    'http://*.ngrok-free.app',   # También permite HTTP por si acaso
]

# Configuración CORS para ngrok
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://9b30-189-129-101-120.ngrok-free.app",  # Tu dominio específico
]

# Permitir cookies en subdominios
CORS_ALLOW_CREDENTIALS = True

# Configuración adicional para ngrok
SECURE_CROSS_ORIGIN_OPENER_POLICY = None

# ===========================================
# CONFIGURACIÓN PARA DOCKER - AGREGADO
# ===========================================

# Sobrescribir configuración de base de datos si estamos en Docker
if os.getenv('DB_HOST'):  # Solo si hay variables de entorno de Docker
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'evento_qr_db'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', 'Saladin0'),
            'HOST': os.getenv('DB_HOST', 'db'),  # 'db' para Docker
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
    print("🐳 Usando configuración de base de datos para Docker")

# Agregar puertos para Docker al CORS y CSRF
if os.getenv('DB_HOST'):  # Solo en Docker
    CORS_ALLOWED_ORIGINS += [
        "http://localhost:3012",
        "http://127.0.0.1:3012",
    ]
    
    CSRF_TRUSTED_ORIGINS += [
        'http://localhost:3012',
        'http://127.0.0.1:3012',
    ]
    
    # Agregar WhiteNoise para servir archivos estáticos en Docker
    if 'whitenoise.middleware.WhiteNoiseMiddleware' not in MIDDLEWARE:
        MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

       
    
    print("🐳 Configuración Docker aplicada - Puerto 3012 habilitado")

    os.environ['TZ'] = 'America/Mexico_City'
