# Generated by Django 5.2.1 on 2025-07-03 22:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('puesto_cargo', models.CharField(max_length=150, verbose_name='Puesto o cargo')),
                ('fotografia', models.ImageField(help_text='Sube una foto del invitado', upload_to='fotos_invitados/', verbose_name='Fotografía')),
                ('token_qr', models.CharField(blank=True, max_length=100, unique=True)),
                ('qr_generado', models.BooleanField(default=False, verbose_name='QR generado')),
                ('qr_imagen', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='Código QR')),
                ('asistio', models.BooleanField(default=False, verbose_name='¿Asistió?')),
                ('fecha_hora_entrada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de entrada')),
                ('escaneado_por', models.CharField(blank=True, max_length=100, verbose_name='Escaneado por (dispositivo/usuario)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invitado',
                'verbose_name_plural': 'Invitados',
                'ordering': ['nombre_completo'],
            },
        ),
    ]
